apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: deckhub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: deckhub/web:1.0.0-alpha1
        imagePullPolicy: Always
        name: web
        env:
          - name: Redis__Host
            value: 'redis'
          - name: Runtime__IdentityPathPrefix
            value: 'i'
          - name: AppMetrics__InfluxDbServer
            value: 'http://rlmetrics.eastus.cloudapp.azure.com:8086'
          - name: AppMetrics__InfluxDbDatabase
            value: 'deckhub'
          - name: Security__ApiKeyHashPhrase
            valueFrom:
              secretKeyRef:
                name: api-key
                key: hashPhrase
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: deckhub
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: web
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  namespace: deckhub
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: deckhub.app
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80