apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: slidable
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: slidable/web:1.1.0
        imagePullPolicy: Always
        name: web
        env:
          - name: Services__Shows__BaseUrl
            value: "http://shows"
          - name: Services__Slides__BaseUrl
            value: "http://slides"
          - name: Services__Notes__BaseUrl
            value: "http://notes"
          - name: Services__Questions__BaseUrl
            value: "http://questions"
          - name: Security__ApiKeyHashPhrase
            valueFrom:
              secretKeyRef:
                name: api-key
                key: hashPhrase
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: slidable
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: web
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  namespace: slidable
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: slidable.io
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80